### ISSUE TITLE
How do I install and run?

### ISSUE THREAD

**Issue by jeffreylm** [kevinhermawan/Ollamac#41]
There is no information on how to install and get it up and running on the release page.

**Comment by Alexandre2006** [comment]
You can download Ollamac using the `.dmg` file provider under `Assets` on the releases page.

You may be told that you are not allowed to open `Ollamac.dmg` due to security reasons. To bypass this, open the `System Settings` app and look for the `Privacy and Security` section. In the Privacy and Security section, find the button labeled "Open Anway" to open the Ollamac installer.

Once the Ollamac installer, the installation is as simple as dragging and dropping the Ollamac icon into the Applications folder to its right.

Then, run Ollamac as you would with any other app.

NOTE: Ollamac requires Ollama to be installed. You can download it here [Ollama Download Page](https://ollama.ai/). The Ollama installation process is very similar to the Ollamac installation process.

NOTE: A model must be downloaded. To download models, visit the [Ollama Model Page](https://ollama.ai/library/llama2/tags) and run `ollama pull [MODEL NAME]` in your terminal.

**Comment by kevinhermawan** [comment]
Thanks @Alexandre2006 😄
